---
- name: "Copy Backend file"
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "Unarchive backend file"
  ansible.builtin.shell: tar -xzf artifact.tar.gz
  args:
    chdir: /home/ubuntu

- name: "installing node"
  shell: |
      cd /home/ubuntu/backend
      npm i
- name: "excuting with pm"
  shell: |
      cd /home/ubuntu/backend/dist
      export ENVIRONMENT=production
      export NODE_ENV=production
      export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}"
      export TYPEORM_ENTITIES=/home/ubuntu/dist/modules/domain/**/*.entity.js
      export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME') }}"
      export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE') }}"
      export TYPEORM_CONNECTION="{{ lookup('env', 'TYPEORM_CONNECTION')}}"  
      export TYPEORM_PORT="{{ lookup('env', 'TYPEORM_PORT')}}"
      export TYPEORM_MIGRATIONS="{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
      export TYPEORM_MIGRATIONS_DIR="{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"
      pm2 stop default
      pm2 start main.js
- name: "pm2 server start"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu